---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cephfs-csi-nodeplugin
  # FDC: 增加命名空间
  namespace: multi-csi

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  # FDC： 更新名称
  name: external-cephfs-csi-nodeplugin
rules:
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get"]

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  # FDC： 更新名称
  name: external-cephfs-csi-nodeplugin
subjects:
  - kind: ServiceAccount
    name: cephfs-csi-nodeplugin
    # FDC: 更新名称
    namespace: multi-csi
roleRef:
  kind: ClusterRole
  # FDC: 更新名称
  name: external-cephfs-csi-nodeplugin
  apiGroup: rbac.authorization.k8s.io
