---
apiVersion: v1
kind: Secret
metadata:
  name: csi-cephfs-secret
  namespace: nebula-system
stringData:
  # Required for statically provisioned volumes
  # FDC: 需替换，需是原字符串，非Base64编码
  userID: <plaintext ID>
  userKey: <Ceph auth key corresponding to ID above>

  # Required for dynamically provisioned volumes
  # FDC: 需替换，需是原字符串，非Base64编码
  adminID: <plaintext ID>
  adminKey: <Ceph auth key corresponding to ID above>
