---
apiVersion: v1
kind: Secret
metadata:
  # FDC: 更新名称
  name: external-cephfs-secret
  # FDC: 更新名称
  namespace: multi-csi
stringData:
  # Required for statically provisioned volumes
  userID: <plaintext ID>
  userKey: <Ceph auth key corresponding to ID above>

  # Required for dynamically provisioned volumes
  adminID: <plaintext ID>
  adminKey: <Ceph auth key corresponding to ID above>
